FindaMovie/urls.py
from django.contrib import admin
from django.urls import path

from movie import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.get_movie_list, name='home'), # send to login form
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
	path('register/', views.registerPage, name='signup'),
	path('login/', views.loginPage, name='signin'),  
	path('logout/', views.logoutUser, name='signout'),
]

movie/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # path('home/', name='home'), # go to this after login
    # path('transaction/', name='transaction'), # for transaction, maybe
    # path('register/', views.UserFormView.as_view(), name='register'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from movie.views import get_name,get_recomm,get_recomm,genre_based,get_movie_list
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', get_movie_list, name='home'),
    path('accounts/', include('accounts.urls')),
    path('recom/', get_recomm, name ='recom'),
    path('genre/', genre_based, name ='genre'),
    path('form/', get_name, name ='form'),


]

accounts/models.py
from django.db import models

# Create your models here.

movie/models.py
from django.db import models
# Create your models here.


class Movie(models.Model):
    title = models.CharField(max_length=1000)
    score = models.FloatField()
    popularity = models.FloatField()
    url=models.CharField(max_length=1000, default='')
    img = models.CharField(max_length=1000, default='')
    adventure_genre = models.BooleanField(default=False)
    comedy_genre = models.BooleanField(default=False)
    thriller_genre = models.BooleanField(default=False)
    action_genre = models.BooleanField(default=False)
    romance_genre = models.BooleanField(default=False)
    animation_genre = models.BooleanField(default=False)
    def __str__(self):
        return self.title

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

movie/forms.py
from django import forms

class NameForm(forms.Form):
    title = forms.CharField(label='title', max_length=100)

accounts/views.py
from django.shortcuts import render, redirect 
#from django.http import HttpResponse
#from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .forms import CreateUserForm
# Create your views here.


def registerPage(request):
	if request.user.is_authenticated:
		return redirect('home')
	else:
		form = CreateUserForm()
		if request.method == 'POST':
			form = CreateUserForm(request.POST)
			if form.is_valid():
				form.save()
				user = form.cleaned_data.get('username')
				messages.success(request, 'Account was created for ' + user)

				return redirect('accounts:signin')
			

		context = {'form':form}
		return render(request, 'accounts/register.html', context)

def loginPage(request):
	if request.user.is_authenticated:
		return redirect('home')
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			password =request.POST.get('password')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user)
				return redirect('home')
			else:
				messages.info(request, 'Username OR password is incorrect')

		context = {}
		return render(request, 'accounts/signin.html', context)

def logoutUser(request):
	logout(request)
	return redirect('accounts:signin')

#@login_required(login_url='accounts:signin')
def home(request):
    if request.user.is_authenticated:
        context = {'user':request.user}
        return render(request, 'accounts/home.html', context)
    else:
        return render(request, 'accounts/home.html')

movie/views.py
# Create your views here.
from .models import Movie
from django.shortcuts import render, redirect
import requests
from .forms import NameForm


def get_movie_list(request):
    if request.method == 'GET':
        response = requests.post('http://127.0.0.1:5000/popular')
        dictn = response.json()
        print(dictn)
        return render(request, 'movie/home.html',
                      {'movie_list': dictn})

def get_recomm(request):
    if request.method == 'GET':
        response = requests.post('http://127.0.0.1:5000/', json={"title": "The Dark Knight Rises"})
        print(response.json()) # This should contain the returned data
        return render(request, 'movie/recommendation.html',
                      {'movie_list': response.json()})

def genre_based(request):
    if request.method == 'GET':
        response = requests.post('http://127.0.0.1:5000/genre', json={"title": "The Dark Knight Rises"})
        print(response.json()) # This should contain the returned data
        return render(request, 'movie/genre.html',
            {'movie_list': response.json()})

def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            title = form.cleaned_data['title']
            response = requests.post('http://127.0.0.1:5000/genre', json={"title": title})
            print(response.json()) # This should contain the returned data
            return render(request, 'movie/genre.html',
                {'movie_list': response.json()})

    # if a GET (or any other method) we'll create a blank form
    else:
        form = NameForm()

    return render(request, 'movie/form.html', {'form': form})

accounts/templates/accounts/home.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
</head>

<body>

    {% if user.is_authenticated %}
        <span>username is: {{ user.get_username }}</span>
        <a href="{% url 'accounts:signout' %}">Sign out Here!</a>
    {% else %}
        <a href="{% url 'accounts:signin' %}">Sign in now!</a>
    {% endif %}

    
</body>
</html>

accounts/templates/accounts/signin.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>

							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>

								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}			
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'accounts:signup' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

movie/templates/movie/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Movie Recommender {% endblock %}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<main>
    {% block content %}
    {% endblock %}
</main>

</body>
</html>

movie/templates/movie/form.html
{% extends 'movie/base.html' %}
{% load static %}
{% block title %} Recommendations {% endblock %}

{% block content %}
<style>
body {
    margin: 0;
    padding: 0;
    height: 100%;
    background: black !important;
    color:white;
}
</style>
{% if user.is_authenticated %}
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" style="color:yellow; font-weight: bold; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;" href="#">Popcorn Time</a>
        </div>

        
        <ul class="nav navbar-nav navbar-right">
            <li><a class="btn btn-primary" style="color:white;"" href="{% url 'accounts:signout' %}">Sign out</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a class="btn btn-primary" style="color:white;"" href="{% url 'form' %}">Genre</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a class="btn btn-primary" style="color:white;"" href="{% url 'home' %}">Popular</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a style="color:greenyellow;font-weight: bold; font-size: large;">User: {{ user.get_username }}</a></li>
        </ul>
   
    </div>
</nav>

<h3 style="color:red;"><center>Welcome to Popcorn Time!</center></h3> <br>
<center><img height=100 width=100 src="{% static 'movie/popcorn.png' %}"></center>
<h3 style="color:red;"><center>Movie suggestions based on your choice</center></h3> <br>

<form action="{% url 'form' %}" method="post">
    {% csrf_token %}
    <label for="title">Enter Movie Name : </label>
    <input id="title" type="text" name="title">
    <input type="submit" value="OK" style="color:black">

</form>
{% endif %}
{% endblock %}

movie/templates/movie/genre.html
{% extends 'movie/base.html' %}
{% load static %}
{% block title %} Recommendations {% endblock %}

{% block content %}
<style>
body {
    margin: 0;
    padding: 0;
    height: 100%;
    background: black !important;
    color:white;
}
</style>
{% if user.is_authenticated %}
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" style="color:yellow; font-weight: bold; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;" href="#">Popcorn Time</a>
        </div>

        
        <ul class="nav navbar-nav navbar-right">
            <li><a class="btn btn-primary" style="color:white;"" href="{% url 'accounts:signout' %}">Sign out</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a class="btn btn-primary" style="color:white;"" href="{% url 'form' %}">Genre</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a class="btn btn-primary" style="color:white;"" href="{% url 'home' %}">Popular</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a style="color:greenyellow;font-weight: bold; font-size: large;">User: {{ user.get_username }}</a></li>
        </ul>
   
    </div>
</nav>

<h3 style="color:red;"><center>Welcome to Popcorn Time!</center></h3> <br>
<center><img height=100 width=100 src="{% static 'movie/popcorn.png' %}"></center>
<h3 style="color:red;"><center>Movies based on the genre of your choice</center></h3> <br>
<ul style="list-style-type: none;font-family: Verdana, Geneva, Tahoma, sans-serif;"><center>
{% for movie in movie_list.values %}
    <li style="margin:5px; padding-top:10px;padding-bottom:10px; background-color:crimson;">
        <!-- <img src="{{ movie.img }}" width=50 height=50>
        <div style="text-align: center;">
        <a href="{{movie.url}}" style="color:white; font-weight: bold;">{{ movie }}</a>
        <br>(
        {% if movie.adventure_genre%}
        <span>Adventure, </span>
        {% endif %}
        {% if movie.comedy_genre%}
        <span>Comedy, </span>
        {% endif %}
        {% if movie.thriller_genre%}
        <span>Thriller, </span>
        {% endif %}
        {% if movie.action_genre%}
        <span>Action, </span>
        {% endif %}
        {% if movie.romance_genre%}
        <span>Romance, </span>
        {% endif %}
        {% if movie.animation_genre %}
        <span>Animation, </span>
        {% endif %}
        )   
    </div> -->
    {{ movie }}
    
    </li>
{% endfor %}
</ul>
</center>

{% else %}

<nav class="navbar navbar-light" style="background-color: red;">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" style="color:yellow; font-weight: bold; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;" href="#">Popcorn Time</a>
        </div>
    <ul class="nav navbar-nav navbar-right">
        <li><a class="btn btn-primary" style="color:white;" href="{% url 'accounts:signin' %}">Sign in</a></li>
    </ul>
    </div>
</nav>

<center><img height=150 width=150 src="{% static 'movie/popcorn.png' %}"></center>
<center><h1 style="color:yellow; font-weight: bold; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;">Popcorn Time</h1>
    <h3 style="color:white; font-weight: bold; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;">Delve into the depths of drama and search for your tastes in movies!</h3>
    <h3 style="color:white; font-weight: bold; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;">Create an account today and get access to the trends!</h3></center>

    <form action="/your-name/" method="post">
        <label for="your_name">Your name: </label>
        <input id="your_name" type="text" name="your_name" value="{{ current_name }}">
        <input type="submit" value="OK">
    </form>
{% endif %}


{% endblock %}

movie/templates/movie/genreform.html
{% extends 'movie/base.html' %}
{% load static %}
{% block title %} Recommendations {% endblock %}

{% block content %}
<style>
body {
    margin: 0;
    padding: 0;
    height: 100%;
    background: black !important;
    color:white;
}
</style>
{% if user.is_authenticated %}
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" style="color:yellow; font-weight: bold; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;" href="#">Popcorn Time</a>
        </div>

        
        <ul class="nav navbar-nav navbar-right">
            <li><a class="btn btn-primary" style="color:white;"" href="{% url 'accounts:signout' %}">Sign out</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a class="btn btn-primary" style="color:white;"" href="{% url 'form' %}">Genre</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a class="btn btn-primary" style="color:white;"" href="{% url 'home' %}">Popular</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a style="color:greenyellow;font-weight: bold; font-size: large;">User: {{ user.get_username }}</a></li>
        </ul>
   
    </div>
</nav>

<h3 style="color:red;"><center>Welcome to Popcorn Time!</center></h3> <br>
<center><img height=100 width=100 src="{% static 'movie/popcorn.png' %}"></center>
<h3 style="color:red;"><center>Movie suggestions based on your choice</center></h3> <br>

<form action="{% url 'form' %}" method="post">
    {% csrf_token %}
    <label for="title">Enter Movie Name : </label>
    <input id="title" type="text" name="title">
    <input type="submit" value="OK" style="color:black">

</form>
{% endif %}
{% endblock %}

movie/templates/movie/home.html
{% extends 'movie/base.html' %}
{% load static %}
{% block title %} Home {% endblock %}

{% block content %}
<style>
body {
    margin: 0;
    padding: 0;
    height: 100%;
    background: black !important;
    color:white;
}
</style>
{% if user.is_authenticated %}
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" style="color:yellow; font-weight: bold; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;" href="#">Popcorn Time</a>
        </div>

        
        <ul class="nav navbar-nav navbar-right">
            <li><a class="btn btn-primary" style="color:white;"" href="{% url 'accounts:signout' %}">Sign out</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a class="btn btn-primary" style="color:white;"" href="{% url 'form' %}">Genre</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a class="btn btn-primary" style="color:white;"" href="{% url 'home' %}">Popular</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a style="color:greenyellow;font-weight: bold; font-size: large;">User: {{ user.get_username }}</a></li>
        </ul>
   
    </div>
</nav>

<h3 style="color:red;"><center>Welcome to Popcorn Time!</center></h3> <br>
<center><img height=100 width=100 src="{% static 'movie/popcorn.png' %}"></center>
<h3 style="color:red;"><center>Trending Movies</center></h3> <br>
<ul style="list-style-type: none;font-family: Verdana, Geneva, Tahoma, sans-serif;"><center>
{% for movie in movie_list.values %}
    <li style="margin:5px; padding-top:10px;padding-bottom:10px; background-color:crimson;">
        <!-- <img src="{{ movie.img }}" width=50 height=50>
        <div style="text-align: center;">
        <a href="{{movie.url}}" style="color:white; font-weight: bold;">{{ movie }}</a>
        <br>(
        {% if movie.adventure_genre%}
        <span>Adventure, </span>
        {% endif %}
        {% if movie.comedy_genre%}
        <span>Comedy, </span>
        {% endif %}
        {% if movie.thriller_genre%}
        <span>Thriller, </span>
        {% endif %}
        {% if movie.action_genre%}
        <span>Action, </span>
        {% endif %}
        {% if movie.romance_genre%}
        <span>Romance, </span>
        {% endif %}
        {% if movie.animation_genre %}
        <span>Animation, </span>
        {% endif %}
        )   
    </div> -->
    {{ movie }}
    
    </li>
{% endfor %}
</ul>
</center>

{% else %}

<nav class="navbar navbar-light" style="background-color: red;">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" style="color:yellow; font-weight: bold; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;" href="#">Popcorn Time</a>
        </div>
    <ul class="nav navbar-nav navbar-right">
        <li><a class="btn btn-primary" style="color:white;" href="{% url 'accounts:signin' %}">Sign in</a></li>
    </ul>
    </div>
</nav>

<center><img height=150 width=150 src="{% static 'movie/popcorn.png' %}"></center>
<center><h1 style="color:yellow; font-weight: bold; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;">Popcorn Time</h1>
    <h3 style="color:white; font-weight: bold; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;">Delve into the depths of drama and search for your tastes in movies!</h3>
    <h3 style="color:white; font-weight: bold; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;">Create an account today and get access to the trends!</h3></center>

    <form action="/your-name/" method="post">
        <label for="your_name">Your name: </label>
        <input id="your_name" type="text" name="your_name" value="{{ current_name }}">
        <input type="submit" value="OK">
    </form>
{% endif %}


{% endblock %}

movie/templates/movie/recommendation.html
{% extends 'movie/base.html' %}
{% load static %}
{% block title %} Recommendations {% endblock %}

{% block content %}
<style>
body {
    margin: 0;
    padding: 0;
    height: 100%;
    background: black !important;
    color:white;
}
</style>
{% if user.is_authenticated %}
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" style="color:yellow; font-weight: bold; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;" href="#">Popcorn Time</a>
        </div>

        
        <ul class="nav navbar-nav navbar-right">
            <li><a class="btn btn-primary" style="color:white;"" href="{% url 'accounts:signout' %}">Sign out</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a class="btn btn-primary" style="color:white;"" href="{% url 'form' %}">Genre</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a class="btn btn-primary" style="color:white;"" href="{% url 'home' %}">Popular</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a style="color:greenyellow;font-weight: bold; font-size: large;">User: {{ user.get_username }}</a></li>
        </ul>
   
    </div>
</nav>

<h3 style="color:red;"><center>Welcome to Popcorn Time!</center></h3> <br>
<center><img height=100 width=100 src="{% static 'movie/popcorn.png' %}"></center>
<h3 style="color:red;"><center>Our Suggestions</center></h3> <br>
<ul style="list-style-type: none;font-family: Verdana, Geneva, Tahoma, sans-serif;"><center>
{% for movie in movie_list.values %}
    <li style="margin:5px; padding-top:10px;padding-bottom:10px; background-color:crimson;">
        <!-- <img src="{{ movie.img }}" width=50 height=50>
        <div style="text-align: center;">
        <a href="{{movie.url}}" style="color:white; font-weight: bold;">{{ movie }}</a>
        <br>(
        {% if movie.adventure_genre%}
        <span>Adventure, </span>
        {% endif %}
        {% if movie.comedy_genre%}
        <span>Comedy, </span>
        {% endif %}
        {% if movie.thriller_genre%}
        <span>Thriller, </span>
        {% endif %}
        {% if movie.action_genre%}
        <span>Action, </span>
        {% endif %}
        {% if movie.romance_genre%}
        <span>Romance, </span>
        {% endif %}
        {% if movie.animation_genre %}
        <span>Animation, </span>
        {% endif %}
        )   
    </div> -->
    {{ movie }}
    
    </li>
{% endfor %}
</ul>
</center>

{% else %}

<nav class="navbar navbar-light" style="background-color: red;">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" style="color:yellow; font-weight: bold; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;" href="#">Popcorn Time</a>
        </div>
    <ul class="nav navbar-nav navbar-right">
        <li><a class="btn btn-primary" style="color:white;" href="{% url 'accounts:signin' %}">Sign in</a></li>
    </ul>
    </div>
</nav>

<center><img height=150 width=150 src="{% static 'movie/popcorn.png' %}"></center>
<center><h1 style="color:yellow; font-weight: bold; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;">Popcorn Time</h1>
    <h3 style="color:white; font-weight: bold; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;">Delve into the depths of drama and search for your tastes in movies!</h3>
    <h3 style="color:white; font-weight: bold; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;">Create an account today and get access to the trends!</h3></center>

    <form action="/your-name/" method="post">
        <label for="your_name">Your name: </label>
        <input id="your_name" type="text" name="your_name" value="{{ current_name }}">
        <input type="submit" value="OK">
    </form>
{% endif %}


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Movie Recommender {% endblock %}</title>
</head>
<body>
<main>
    {% block content %}
    {% endblock %}
</main>

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}

<h3>Popular Movies</h3> <br>
{% for movie in movie_list %}
<h5>{{ movie }}</h5><br>
{% endfor %}

{% endblock %}